# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [3]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [4]:
print(np.version.version
print(np.__version__)

1.12.1
1.12.1


### Display array elements in reverse order

In [13]:
array = np.arange(10)
print(array[::-1])
print(np.flip(array, 0))
array_reverse = np.flip(array, 0)

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


### Triple elements in array

In [15]:
array_reverse3 = array_reverse * 3
print(array_reverse3)

[27 24 21 18 15 12  9  6  3  0]


### Create array with 20 zeros; every fifth element equals four

In [32]:
np_zero = np.zeros(20)
np_index = np.arange(20) + 1
zero_mod_5_mask = 0 == (np_index % 5)

np_zero_5 = zero_mod_5_mask.astype(int) * 4

print(np_zero_5)




[0 0 0 0 4 0 0 0 0 4 0 0 0 0 4 0 0 0 0 4]


In [5]:
my_array = np.zeros(20)
my_array[0::5] = 4
my_array

array([ 4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,
        0.,  0.,  4.,  0.,  0.,  0.,  0.])

### Transpose the rows and columns

In [36]:
array = np.arange(20).reshape(4,5)
print(array)
print(array.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


### Create a 5x5 identity matrix with integer components

In [6]:
a = np.eye(5)

print(a)
print(a.astype(int))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [7]:
my_matrix = np.asmatrix(np.eye(5, dtype='int'))
my_matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [44]:
a = np.random.rand(30)

print(a)
print(np.mean(a))

[ 0.72  0.48  0.33  0.98  0.33  0.94  0.64  0.21  0.34  0.29  0.02  0.36
  0.47  0.78  0.71  0.08  0.54  0.96  0.54  0.86  0.07  0.94  0.79  0.76
  0.56  0.83  0.78  0.54  0.24  0.21]
0.543010408985


In [8]:
my_random_vector = np.random.random(30)
my_random_vector.mean()

0.47013146698209313

#### Repeat, and visually estimate the mean for the sum of the two means

In [45]:
b = np.random.rand(30)

print(b)
print(np.mean(b))

[ 0.41  0.23  0.45  0.62  0.15  0.4   0.25  0.1   0.1   0.6   0.04  0.28
  0.88  0.9   0.86  0.78  0.25  0.97  0.55  0.26  0.77  0.68  0.02  0.29
  0.71  0.42  0.78  0.99  0.09  0.29]
0.470581639048


#### Repeat, and visually estimate the mean for the sum of the two means

### Create a 2d array with ones on the border and zeros inside the border

In [37]:
my_array = np.zeros(64, dtype=int).reshape(8,8)
#my_array[0 ::-1] = 1
#my_array[0 :-1, 0] = 1
#my_array[-1 :: ] = 1
my_array[0 :-1, -1:] = 0

print(my_array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [38]:
my_bordered_array = np.ones((5,5))
my_bordered_array[1:-1,1:-1] = 0
my_bordered_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### Create an 8x8 checker board with alternating zeros and ones

In [12]:
checker_row1 = [0,1]
checker_row2 = [1,0]

np_checker_row1 = np.asarray(checker_row1)
np_checker_row2 = np.asarray(checker_row2)

np_checker_row1 = np.tile(np_checker_row1, 4)
np_checker_row2 = np.tile(np_checker_row2, 4)

np_checker_2rows = np.append(np_checker_row1, np_checker_row2)

np_checker_all = np.tile(np_checker_2rows, 4)

np_checker_all_reshape = np_checker_all.reshape(8, 8)

print(np_checker_all_reshape)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
my_checker_board = np.zeros((8,8),dtype=int)
my_checker_board[1::2,::2] = 1
my_checker_board[::2,1::2] = 1
print(my_checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Create a sorted vector that contain 'n' random numbers

In [15]:
a = np.sort(np.random.rand(30))
print(a)

[ 0.13  0.14  0.14  0.15  0.23  0.28  0.31  0.42  0.43  0.45  0.45  0.47
  0.48  0.48  0.5   0.61  0.63  0.66  0.77  0.81  0.84  0.84  0.85  0.89
  0.91  0.93  0.93  0.95  0.96  0.96]


### Without sorting, replace largest element in random array with the value 1234

In [27]:
a = np.random.rand(30)

print(np.argmax(a))
print(a)

mx_ind = np.argmax(a)
a[mx_ind] = 1234

print(a)



19
[ 0.74  0.48  0.24  0.16  0.36  0.82  0.25  0.72  0.75  0.46  0.24  0.88
  0.63  0.15  0.79  0.19  0.17  0.59  0.06  0.98  0.5   0.94  0.83  0.89
  0.84  0.07  0.18  0.87  0.2   0.66]
[  7.35e-01   4.78e-01   2.45e-01   1.60e-01   3.64e-01   8.20e-01
   2.51e-01   7.23e-01   7.46e-01   4.59e-01   2.36e-01   8.80e-01
   6.26e-01   1.52e-01   7.92e-01   1.94e-01   1.69e-01   5.93e-01
   6.09e-02   1.23e+03   4.98e-01   9.39e-01   8.30e-01   8.91e-01
   8.41e-01   6.66e-02   1.80e-01   8.70e-01   2.04e-01   6.64e-01]


### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [44]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [37]:
#print(camelot_values)

np_camelot_values = np.asarray(camelot_values)
#print(np_camelot_values)
print(np.sort(np_camelot_values, axis=0))

[['Arthur' '1.7' '38']
 ['Galahad' '1.8' '38']
 ['Lancelot' '1.9' '41']]


In [45]:
camelot_structured_array = np.array(camelot_values, dtype=camelot_dtype)
camelot_sorted_array = np.sort(camelot_structured_array, order='height')
for n in np.arange(camelot_sorted_array.size):
    print (camelot_sorted_array[n])

(b'Galahad',  1.7, 38)
(b'Arthur',  1.8, 41)
(b'Lancelot',  1.9, 38)


### Make an array read-only (immutable)

In [46]:
my_ordinary_array = np.array(np.arange(12))
my_ordinary_array.flags.writeable = False
my_ordinary_array[5] = 1234

ValueError: assignment destination is read-only

### Print enumerated values from a 3x3 NumPy array

In [47]:
my_3_3_array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(my_3_3_array):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
